### ISSUE TITLE
Update link to Issue Tracker

### ISSUE THREAD

**Issue by kputh** [apache/cordova-docs#1166]
# Bug Report

## Problem
The footer of https://cordova.apache.org/ has a link labeled "Issue Tracker" leading to a seemingly semi-abandoned JIRA. I understand issues are currently tracked here, on GitHub. The link should either be updated or removed.

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
I think perhaps the best replacement link might be https://github.com/apache/cordova#filing-a-bug
